apiVersion: kpt.dev/v1
kind: FunctionResultList
metadata:
  name: fnresults
exitCode: 1
items:
  - image: ghcr.io/kptdev/krm-functions-catalog/kubeconform:latest
    stderr: 'failed to evaluate function: error: function failure'
    exitCode: 1
    results:
      - message: got string, want null or integer
        severity: error
        resourceRef:
          apiVersion: v1
          kind: ReplicationController
          name: bob
        field:
          path: spec.replicas
        file:
          path: replicationcontroller.yaml
