apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: test-simple
spec:
  parentRef:
    kind: Organization
    external: test-organization
  layers:
    - environments
    - teams
  config:
    environments:
      - Dev
      - Prod
    teams:
      - Team "One"
      - Team_2
